### ISSUE TITLE
sprout-verifying.key no such file

### ISSUE THREAD

**Issue by evolmk** [Tomas-M/VoteCoin-wallet#1]
Just reporting a bug, i know you're still working on this.  Seems app trying to access these files before they exist...

Prerelease version: `v0.0.2`
OS: `windows 10`

Errors on startup: 
```
ENOENT no such file or directory: \resources\sprout-verifying.key
ENOENT no such file or directory: \resources\sprout-proving.key
```

**Comment by Tomas-M** [comment]
Thanks for testing. I've added there proper redirect support and original zcash URLs for download ...
This should fix everything. Please test new release. If you experience more problems, feel free to reopen this issue.
