### ISSUE TITLE
Loading issue

### ISSUE THREAD

**Issue by spikeyphantom** [Tomas-M/VoteCoin-wallet#3]
![1](https://user-images.githubusercontent.com/16128819/36138483-24aa9e30-10cc-11e8-8214-555320d3cb37.PNG)
almost 8 hours and gui wallet still loading..
can i move my balance from gui wallet to cli wallet?
thank  you

**Comment by Tomas-M** [comment]
Hm, strange. What is in debug.log file? You can find it in 
resources\app\VoteCoin\debug.log

Restart your computer and try again.
If that doesn't help, you can copy wallet.dat file from VoteCoin directory to your CLI wallet's VoteCoin directory. Make sure the wallet is not running when you copy the file.

**Comment by leouch** [comment]
Hi, I have the exact same problem. Have had it for a few days now. I added my debug file. Could you kindly tell me which is the CLI wallet directory so can try and move the wallet.dat file there to see if it works that way. Here is my debug log. Thanks for all the hard work!

[debug.log](https://github.com/Tomas-M/VoteCoin-wallet/files/1720065/debug.log)

**Comment by Tomas-M** [comment]
Thank you. I don't really understand what's wrong.
Please try to erase these directories:
- chainstate
- blocks
Both are in VoteCoin directory.
Then start votecoin.exe. It should resync the blockchain from scratch.

**Comment by leouch** [comment]
Thank you Tomas, erasing  chainstate and blocks worked. Wallet loaded immediately and is fully synced now after resync .
