### ISSUE TITLE
Fix slow running for such a large number of transactions

### ISSUE THREAD

**Issue by sypv84** [Tomas-M/VoteCoin-wallet#4]
Currently my wallet is for mining, so the number of transactions is large, when using software runs very slowly.

**Comment by Tomas-M** [comment]
Yeah that is a problem of the underlaying zcash core. Basically all coins based on bitcoin have such problem, as far as I know, and there is nothing we could do at the moment to improve the performance.

**Comment by sypv84** [comment]
The problem of late addressing has made a lot of exchanges in the past, not the ongoing transactions.
