### ISSUE TITLE
Empty dashboard bug

### ISSUE THREAD

**Issue by Punkoivan** [Tomas-M/VoteCoin-wallet#5]
Hello Tom and Team, could you please take a look at this issue?

Once I loaded my wallet and realized that dashboard is totally empty.
Win10, on my Linux laptop all working perfect.

please let me know if any debug files are needed.

Thanks in advance,
Ivan

P.S. have a trouble attaching screenshot, will add later in a comment.

**Comment by Tomas-M** [comment]
If your wallet is empty, you need to generate addressese and send some coins to them.
Not sure what's the issue here

**Comment by Punkoivan** [comment]
Tom, I have used wallet for a long time and have huge history in it.

I have every day new coins to my wallet and amount is changed, but dashboard is empty.
We discussed it in telegram and it seems not only I have a problem.

Please find screenshot here:
https://drive.google.com/file/d/1eFTm9uPUzGq5nn8urmVI_v7YqT178pmc/view?usp=sharing

**Comment by Tomas-M** [comment]
So basically you can see your balance, but you don't see the transactions anymore?

**Comment by Punkoivan** [comment]
Yes, exaclty!

**Comment by Tomas-M** [comment]
Can you see json files in directory resources\app\settings\ ?
There should be transactions.json, this file should contain past transactions. Maybe try to shutdown wallet, erase the file, and start wallet again. It should recreate the transactions file from blockchain. Basically any of the json files can be safely erased. I am wondering, how big is your transactions.json file if it exists?

Furthermore, you can press F12 when wallet is running to see debug console, maybe there are some errors logged? Thanks

**Comment by Punkoivan** [comment]
Hello Tom,
I've found the next error while loading wallet (in F12 console):
```
lib.js:9 SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at JSON_fromString (lib.js:9)
    at storage_load (lib.js:19)
    at votecoin.js:50
```
errors below are adding continuously:
```
votecoin.js:183 Uncaught TypeError: transactions.push is not a function
    at add_transaction (votecoin.js:183)
    at main.rpc (votecoin.js:248)
    at CallbacksRegistry.apply (D:\PATH_TO_WALLET\resources\electron.asar\comm…:48)
    at EventEmitter.<anonymous> (D:\PATH_TO_WALLET\resources\electron.asar\rend…:299)
    at emitThree (events.js:116)
    at EventEmitter.emit (events.js:197)
add_transaction @ votecoin.js:183
main.rpc @ votecoin.js:248
apply @ D:\PATH_TO_WALLET\resources\electron.asar\comm…:48
(anonymous) @ D:\PATH_TO_WALLET\resources\electron.asar\rend…:299
emitThree @ events.js:116
emit @ events.js:197
votecoin.js:183 Uncaught TypeError: transactions.push is not a function
    at add_transaction (votecoin.js:183)
    at main.rpc (votecoin.js:248)
    at CallbacksRegistry.apply (D:\PATH_TO_WALLET\resources\electron.asar\comm…:48)
    at EventEmitter.<anonymous> (D:\PATH_TO_WALLETb\resources\electron.asar\rend…:299)
    at emitThree (events.js:116)
    at EventEmitter.emit (events.js:197)
```

My transactions.json shows only "NUL" now (notepad++), seize - 259 Kb

Will try delete file, reload wallet and update issue.

Thanks,
Ivan

**Comment by Tomas-M** [comment]
How big is your transactions.json file now? It is possible that if the file is too big, and if the wallet was closed at the middle of writing the file to disk, its content got corrupted and on next load it failed to initiate the transactions array and was confused. I think the proper fix will be for VoteCoin wallet to check if a proper JSON is in the .json file, and if not, initiate it as empty and reload from blockchain automatically.

**Comment by Punkoivan** [comment]
Now it's 71 Kb.

Yes, make sense - check if JSON is valid, then proceed, recreate otherwise.

**Comment by Tomas-M** [comment]
Thank you
