### ISSUE TITLE
The coins are stuck on z-address (bad-txns-joinsplit-requirements-not-met).

### ISSUE THREAD

**Issue by linux-router** [Tomas-M/VoteCoin-wallet#7]
I sent coins from t-address to z-address by two transactions and on the balance of z-address I see this coins, but I can not sent them anywhere. If I try to send the entire amount at once, the wallet gives an error:  
_z_sendmany finished (status=failed, error=**Could not find previous JoinSplit anchor**)_

If I try to send the same two sums that they was transferred to z-address, then wallet gives such an error:
_ERROR: AcceptToMemoryPool: joinsplit requirements not met
z_sendmany finished (status=failed, error=18: **bad-txns-joinsplit-requirements-not-met**)
ERROR: AcceptToMemoryPool: joinsplit requirements not met
z_sendmany finished (status=failed, error=18: **bad-txns-joinsplit-requirements-not-met**)_

VoteCoin version v2.0.1-128
So there's nothing I can do with these coins.

**Comment by linux-router** [comment]
https://github.com/zcash/zcash/issues/2712
Нere it is advised to backup all your private keys, then import all your private keys and then to sync. As I knpw in the GUI Votecoin wallet, there is no possibility to backup private keys, but is it possible to do this in the CLI wallet?

**Comment by Tomas-M** [comment]
Sorry for late reply. It is problematic to import previously exported private keys, sometimes it does not work. So it may not help. Anyway, you can try to export it by using z_exportwallet & z_importwallet, the procedure is the same as for zcash: https://github.com/zcash/zcash/blob/master/doc/wallet-backup.md
